'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Eye,
  Download,
  Share2,
  ZoomIn,
  ZoomOut,
  Maximize,
  FileText,
  Table,
  Code,
  Printer,
  Calendar,
  User,
  Lock,
  File,
} from 'lucide-react';

type ViewerFormat = 'html' | 'json' | 'csv';

interface ReportViewerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  reportId: string;
  reportName: string;
  reportType: string;
  period: string;
  generatedBy: string;
  generatedAt: string;
  availableFormats: ViewerFormat[];
}

const mockReportData = {
  summary: {
    totalEvents: 12543,
    criticalEvents: 23,
    complianceScore: 94,
    lastVerified: '2024-11-07 14:30:00',
    keyFindings: [
      'All security controls are operating effectively',
      'No critical vulnerabilities detected in the audit period',
      'Data encryption is properly configured across all systems',
      'Access controls meet regulatory requirements',
    ],
    recommendations: [
      'Continue monitoring key rotation procedures',
      'Implement additional logging for privileged access',
      'Update incident response procedures',
    ],
  },
  sections: [
    {
      id: 'security',
      title: 'Security Controls',
      status: 'compliant',
      description: 'Assessment of security controls and measures',
      findings: [
        'Firewall rules properly configured',
        'Antivirus software up to date on all endpoints',
        'Multi-factor authentication enforced for all users',
      ],
    },
    {
      id: 'access',
      title: 'Access Management',
      status: 'compliant',
      description: 'Review of user access and permissions',
      findings: [
        'User access reviews conducted quarterly',
        'Privileged access properly managed',
        'No excessive permissions identified',
      ],
    },
    {
      id: 'data',
      title: 'Data Protection',
      status: 'partial',
      description: 'Data encryption and classification',
      findings: [
        'Data at rest encrypted using AES-256',
        'Data in transit encrypted using TLS 1.3',
        'Some legacy systems require encryption upgrade',
      ],
    },
  ],
  events: [
    {
      timestamp: '2024-11-07 14:30:00',
      user: 'admin@acme.com',
      action: 'key_rotated',
      resource: 'key-001',
      result: 'success',
    },
    {
      timestamp: '2024-11-07 14:25:00',
      user: 'admin@acme.com',
      action: 'report_generated',
      resource: 'SOC 2 Report',
      result: 'success',
    },
  ],
};

export function ReportViewer({
  open,
  onOpenChange,
  reportId,
  reportName,
  reportType,
  period,
  generatedBy,
  generatedAt,
  availableFormats,
}: ReportViewerProps) {
  const [activeTab, setActiveTab] = useState('summary');
  const [zoomLevel, setZoomLevel] = useState(100);

  const handlePrint = () => {
    window.print();
  };

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
  };

  const handleZoomIn = () => {
    setZoomLevel((prev) => Math.min(prev + 25, 200));
  };

  const handleZoomOut = () => {
    setZoomLevel((prev) => Math.max(prev - 25, 50));
  };

  const getFormatIcon = (format: ViewerFormat) => {
    switch (format) {
      case 'html':
        return <FileText className="h-4 w-4" />;
      case 'json':
        return <Code className="h-4 w-4" />;
      case 'csv':
        return <Table className="h-4 w-4" />;
      default:
        return <File className="h-4 w-4" />;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'compliant':
        return <Badge variant="outline" className="text-green-600">Compliant</Badge>;
      case 'partial':
        return <Badge variant="outline" className="text-yellow-600">Partial Compliance</Badge>;
      case 'non-compliant':
        return <Badge variant="destructive">Non-Compliant</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-6xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>{reportName}</DialogTitle>
          <DialogDescription>
            {reportType} • {period} • Generated by {generatedBy} on {generatedAt}
          </DialogDescription>
        </DialogHeader>

        <div className="flex items-center gap-2 pb-4 border-b">
          <Button variant="outline" size="sm" onClick={handleZoomOut} disabled={zoomLevel <= 50}>
            <ZoomOut className="h-4 w-4" />
          </Button>
          <span className="text-sm">{zoomLevel}%</span>
          <Button variant="outline" size="sm" onClick={handleZoomIn} disabled={zoomLevel >= 200}>
            <ZoomIn className="h-4 w-4" />
          </Button>
          <div className="h-4 w-px bg-gray-300 mx-2" />
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>
          <Button variant="outline" size="sm" onClick={handleShare}>
            <Share2 className="h-4 w-4 mr-2" />
            Share
          </Button>
          <div className="flex-1" />
          <div className="flex items-center gap-2">
            {availableFormats.map((format) => (
              <Button key={format} variant="outline" size="sm">
                {getFormatIcon(format)}
                <span className="ml-2 capitalize">{format}</span>
              </Button>
            ))}
            <Button size="sm">
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto" style={{ zoom: zoomLevel / 100 }}>
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="summary">Summary</TabsTrigger>
              <TabsTrigger value="sections">Sections</TabsTrigger>
              <TabsTrigger value="events">Events</TabsTrigger>
              <TabsTrigger value="raw">Raw Data</TabsTrigger>
            </TabsList>

            <TabsContent value="summary" className="space-y-4 mt-4">
              <Card>
                <CardHeader>
                  <CardTitle>Executive Summary</CardTitle>
                  <CardDescription>Key metrics and findings</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-blue-50 rounded-lg">
                      <p className="text-sm text-blue-600">Total Events</p>
                      <p className="text-2xl font-bold text-blue-900">
                        {mockReportData.summary.totalEvents.toLocaleString()}
                      </p>
                    </div>
                    <div className="p-4 bg-red-50 rounded-lg">
                      <p className="text-sm text-red-600">Critical Events</p>
                      <p className="text-2xl font-bold text-red-900">
                        {mockReportData.summary.criticalEvents}
                      </p>
                    </div>
                    <div className="p-4 bg-green-50 rounded-lg">
                      <p className="text-sm text-green-600">Compliance Score</p>
                      <p className="text-2xl font-bold text-green-900">
                        {mockReportData.summary.complianceScore}%
                      </p>
                    </div>
                    <div className="p-4 bg-gray-50 rounded-lg">
                      <p className="text-sm text-gray-600">Last Verified</p>
                      <p className="text-sm font-medium text-gray-900">
                        {mockReportData.summary.lastVerified}
                      </p>
                    </div>
                  </div>

                  <div>
                    <h4 className="font-semibold mb-2">Key Findings</h4>
                    <ul className="space-y-2">
                      {mockReportData.summary.keyFindings.map((finding, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <div className="h-2 w-2 rounded-full bg-green-500 mt-2" />
                          <span className="text-sm">{finding}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-semibold mb-2">Recommendations</h4>
                    <ul className="space-y-2">
                      {mockReportData.summary.recommendations.map((rec, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <div className="h-2 w-2 rounded-full bg-blue-500 mt-2" />
                          <span className="text-sm">{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="sections" className="space-y-4 mt-4">
              {mockReportData.sections.map((section) => (
                <Card key={section.id}>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div>
                        <CardTitle>{section.title}</CardTitle>
                        <CardDescription>{section.description}</CardDescription>
                      </div>
                      {getStatusBadge(section.status)}
                    </div>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {section.findings.map((finding, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <div className="h-2 w-2 rounded-full bg-gray-400 mt-2" />
                          <span className="text-sm">{finding}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </TabsContent>

            <TabsContent value="events" className="space-y-4 mt-4">
              <Card>
                <CardHeader>
                  <CardTitle>Audit Events</CardTitle>
                  <CardDescription>
                    Events related to this compliance report
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {mockReportData.events.map((event, index) => (
                      <div key={index} className="p-3 border rounded-lg">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Calendar className="h-4 w-4 text-gray-400" />
                            <span className="text-sm font-medium">{event.timestamp}</span>
                          </div>
                          <Badge variant={event.result === 'success' ? 'outline' : 'destructive'}>
                            {event.result}
                          </Badge>
                        </div>
                        <div className="mt-2 grid grid-cols-2 gap-2 text-sm">
                          <div className="flex items-center gap-2">
                            <User className="h-3 w-3 text-gray-400" />
                            <span>{event.user}</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <Lock className="h-3 w-3 text-gray-400" />
                            <span>{event.action}</span>
                          </div>
                        </div>
                        <div className="mt-1 text-sm text-gray-600">
                          Resource: {event.resource}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="raw" className="space-y-4 mt-4">
              <Card>
                <CardHeader>
                  <CardTitle>Raw Report Data</CardTitle>
                  <CardDescription>
                    Complete report data in JSON format
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <pre className="p-4 bg-gray-100 rounded-lg text-xs overflow-x-auto">
                    {JSON.stringify(mockReportData, null, 2)}
                  </pre>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button>
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
